### PR TITLE
Fix install paths

### PR DESCRIPTION
**Pull request by flipflop97**
I fixed a few things regarding paths:

### setup.py

  - `/usr/bin` is used as the default install location instead of `/bin`
  - `/usr/share` should be used instead of `/share`

### de.wolfvollprecht.UberWriter.desktop

The path to the icon was hardcoded and shouldn't be, linux is able to figure out the right icon path by just the name. This fixes icon packs and the icon just not showing up on non-flatpak installs.  
`/usr/share/uberwriter/media/uberwriter.svg` was thus repaced by just `uberwriter`.

### CODE REVIEW

**Comment by somas95** [comment]
I saw your package on the aur :)
I'll look into this, to not break things with the Flatpak build. I'll do a PKGBUILD for building the last release in the AUR based on yours, so thanks for that! I just noticed that you use as dependencies the gtk3 libraries from Ubuntu, why not to use the mainstream ones?

**Comment by flipflop97** [comment]
Hmm, as far as I know I'm not using the Ubuntu verision of gtk3. Aurweb lists all other packages that also provide gtk3 between parentheses, including some Ubuntu related things. Did you mean that? In that case it shouldn't be a problem as it will default to the upstream gtk3.

**Comment by wolfv** [comment]
@somas95 did you have a chance to check this? 

PR looks good to me! (only the flatpak thing I am also not sure).

**Comment by somas95** [comment]
I'll test it tonight. I had a lot of work to do lately, hence my inactivity here, but I'll catch up soon

**Comment by somas95** [comment]
Soft merged in the refactoring branch: 2b824ee0290f71bc0da24f26819d19976e0da1f9
Some adjustments were needed to maintain flatpak compatibility. Thanks, @flipflop97 !

**Pull request closed without merging**
