### PR TITLE
Fix Shift-Tab Behaviour

### LINKED ISSUE #119: `Shift + Tab` doesn’t work for items
### ENVIROMENT
- Linux distribution: Fedora Silverblue 29
- Desktop Enviroment: Gnome Shell 3.30
- GTK version: 1.2.10

### BUG
When I press `Shift + Tab`, the item gets indented one more step, instead of being un-indented.

### PR DESCRIPTION
**Pull request by lavendthomas**
Fixes #119 by removing the last character if it's `\t` when pressing Shift+Tab

### CODE REVIEW

**Comment by lavendthomas** [comment]
One question I have though : do I have to mess with the undo/redo history? I get the following warning:

```
WARNING:uberwriter: __record_undoable() 'Recording a change without a user action.'
```

If so, what do I have to do?

**Comment by goncalossilva** [comment]
It should work perfectly regardless of the warning. It is there because the "begin user action" and "end user action" signals are missing since the text is edited directly.

I recommend handling this and clearing the warning though, because often when it pops up, there are optimizations to be considered (e.g. joining a few text changes together in the same undo/redo). It would be great to not have false positives so that if any appears, it stands out. It can be cleared like so:

```
with user_action(text_buffer):
	text_buffer.delete(iter, end)
```

**Comment by lavendthomas** [comment]
I can confirm the history's still working. Thanks for the fix and the explanation !

**Comment by somas95** [comment]
I'm gonna do some minor linting before merging it, i.e

- we shouldn't redefine `iter`: https://github.com/UberWriter/uberwriter/blob/5cae9eb68cc98a9665d654347ebe40a4858611e2/uberwriter/text_view.py#L259
- and I'd say this else statement is not necessary: https://github.com/UberWriter/uberwriter/blob/5cae9eb68cc98a9665d654347ebe40a4858611e2/uberwriter/text_view.py#L253
- Maybe we should start using private methods for some things. I'm not so sure about this (I never studied computer science) but I think in this case both "on_shift_tab" and "on_key_press_event" could and should be made private. Along with a /lot/ of methods which I won't touch right now, but from so on this could be considered.

In any case, thanks for this! Maybe we could implement some simple autocompletion (for parenthesis/brackets) in a similar way, intercepting keypresses... but at the same time I have the feeling that that could be done in a more efficient/modular way

**Comment by lavendthomas** [comment]
I just learned that Python has a built-in function called iter, I totally agree we shouldn't refine it.

About the auto-completion, a data structure that would make it more modular is a trie, with the last characters at the top of the tree. It has no advantage for one-character strings, like brackets/parenthesis, but the implementation would also support longer words (if we want to introduce a config for #182, for example).

I have no idea if Gtk has a more efficient function to look at the last few characters, but it'll have to look at the last few characters anyway I guess.

**Comment by somas95** [comment]
Great! I'll look how other projects do it

**Pull request merged**
