### PR TITLE
Ft.preview improvements

### PR DESCRIPTION
**Pull request by somas95**
Awesome work, @goncalossilva
I'll try this

### CODE REVIEW

**Comment by goncalossilva** [comment]
Hi, happy to help! It seems you got ahead of me. :smile: I had not yet submitted this PR as there was a couple more things I wanted to include, but I'll include them separately.

In terms of reviewing this, I'd suggest going commit by commit. They're all independent and focused, and any additional reasoning is included in the commit itself. Considering [this](https://github.com/UberWriter/uberwriter/pull/126/commits/928254e9927a7bd28ae3cddd9dd401437e456058) includes improvements to the CSS, I'd like to show a before/after to make some of them clearer.

Before:
Light theme before
Dark theme before

After:
Light theme after
Dark theme after

The commit description itself contains a more thorough list of changes. :blush: Please let me know if there are any doubts!

**Comment by goncalossilva** [comment]
Sorry, I forgot to include the font files. I was not expecting to PR so quickly so didn't revise the state of the repo. :sweat_smile: Will add them in the fork's `styles` branch.

**Comment by somas95** [comment]
Yep! I have a reasonable explanation to the unmatching background colors from the "after" images; I use the Arc theme and I forgot to include styles for Adwaita too.
Notice that the application changes his color scheme (in the editing view) depending on the current GTK theme (I support Adwaita, Yaru and Arc right now) so providing different styles for the webviews will be necessary

**Comment by somas95** [comment]
While GTK allows some css tricks to do that (https://developer.gnome.org/gtk3/stable/chap-css-overview.html), we will need plain color schemes for the webview. How did you generate the palette for Adwaita? It would be cool to have consistency between your theme and the (new) arc one

**Comment by goncalossilva** [comment]
> Yep! I have a reasonable explanation to the unmatching background colors from the "after" images; I use the Arc theme and I forgot to include styles for Adwaita too.

Ah, I see now why the background was different.

> so providing different styles for the webviews will be necessary

I think this is fine, as long as the list of themes to support remains manageable.

> How did you generate the palette for Adwaita?

The basic theme info came [from here](https://gitlab.gnome.org/GNOME/gtk/tree/master/gtk/theme/Adwaita). I took GitHub's official scheme, calculated the difference between its background (white) and Adwaita's, and applied that difference to the remaining colors. Lastly I used [Delta E](http://zschuessler.github.io/DeltaE/learn/) to ensure the perceptual difference remained consistent throughout all colors.

> It would be cool to have consistency between your theme and the (new) arc one

I am unsure if it would be possible to support multiple themes and still use the same style. I think though that leveraging CSS's custom properties (as done between light / dark) could make this very easy. We can:
* Use a default stylesheet (for Adwaita)
* Have additional stylesheets that override these custom properties whenever we detect a different theme that is supported (eg. for Arc)

In fact, we already have colors for Arc, from the previous CSS, so it would be trivial to add it.

Of course, ideally this would be all automated, but I am honestly unsure if it can be done / how to do it, and for 2/3 themes I am unsure if it's worth the added complexity.

**Comment by goncalossilva** [comment]
To keep things easier I have submitted a PR with the missing fonts + responsive preview here: #127

Later today (or tomorrow) I will work a fix for the issue with Arc that you outlined above, using the approach mentioned before, for you to review.

**Pull request merged**
