### PR TITLE
Fix regex for horizontal rules

### LINKED ISSUE #154: Metadata blocks incorrectly formatted
(uberwriter-git-2.2.0.beta1.4.r0.g181af44 on Archlinux w/ GTK 3.24.8)

It looks like Pandoc's `yaml_metadata_block` syntax is not recognized:

```markdown
# Giriş

---
author: Greg Strawbridge
---

Benim teolojik köşkümde birçok oda mevcut.
```

...results in rendering like this:

image

### PR DESCRIPTION
**Pull request by somas95**
Fix regex for horizontal rules
(yaml metadata delimiters should not be counted as rules)

### CODE REVIEW

**Comment by somas95** [comment]
@goncalossilva if you want to take a look, I removed some bits of your last change to that regex line. I think they're not important, but let me know if they're

**Comment by goncalossilva** [comment]
Hey @somas95! Everything has a purpose. :blush: I don't know much about #754 in specific, but this change breaks rules at start and end of documents.

Correct: https://cl.ly/f1a53ef4a7f4/gnome-shell-screenshot-LHFWE0.png
This branch: https://cl.ly/ad134f964883/gnome-shell-screenshot-TY9TE0.png

Another problem is that it can grab paragraphs that don't belong to it, and make the counting less accurate.

Could you tell me what exactly is the goal?

**Comment by goncalossilva** [comment]
YAML metadata delimiters is not part of markdown, so I wonder if this is something we want to support... if we do, here is a slightly cleaner approach:

	HORIZONTAL_RULE = re.compile(
    	r"(?:^|\n{2,})(?P<symbols> {0,3}[*\-_]{3,} *)(?:\n{2,}|$)")

This still reduces the regexp accuracy for horizontal rules (as they only need a single paragraph above), but it's a less breaking change.

**Comment by somas95** [comment]
That's why I thought on pinging you, I was sure that was there for something...

I think no metadata format is part of markdown, but YAML seems to be the more "standarized" one, and pandoc supports it (but I think we would have to enable it). 

Also, for rules with "*" or "_" you only need a single paragraph above, but with "-" you're delimiting a heading, so this would fix that too

Thanks for the input!

**Comment by goncalossilva** [comment]
Yeah, looks great. Good point about delimiting headings. I think we can merge this. :+1:

**Pull request merged**
