### PR TITLE
Various improvements

### LINKED ISSUE #17: feature request: add commonmark support!
plz! :-)

### LINKED ISSUE #75: UberWriter power consumption seems high
### ENVIROMENT
- Linux distribution: Fedora 28
- Desktop Enviroment: GNOME on Xorg
- DE version: gnome-shell-3.28.3-1.fc28.x86_64
- GTK version: using Flatpak:
```
flatpak info org.gnome.Platform/x86_64/3.28
Ref: runtime/org.gnome.Platform/x86_64/3.28
ID: org.gnome.Platform
Arch: x86_64
Branch: 3.28
Origin: flathub
Active commit: cc7c2dd516160674998803e6ed6838091d628a3d25ff7465485ddecfb9f4363f
Latest commit: f5ad47d93872b617a6a05227d82e04481bc5a236c7299d04005e3c1f306f76d8
Parent: -
Location: /var/lib/flatpak/runtime/org.gnome.Platform/x86_64/3.28/cc7c2dd516160674998803e6ed6838091d628a3d25ff7465485ddecfb9f4363f
```

```
❯ flatpak info de.wolfvollprecht.UberWriter/x86_64/stable
Ref: app/de.wolfvollprecht.UberWriter/x86_64/stable
ID: de.wolfvollprecht.UberWriter
Arch: x86_64
Branch: stable
Origin: flathub
Collection ID: org.flathub.Stable
Date: 2018-07-27 18:08:26 +0000
Subject: v2.1.2 (4a6693ce)
Commit: 5f07056aad3ca18f717f05358cbf91cc4eaeb376a156a730fc83089fe4f9d6cf
Parent: c22b291a267f5176ee7876abc9de530f5ec3c8a12af20ba1b69d811377ede681
Location: /var/lib/flatpak/app/de.wolfvollprecht.UberWriter/x86_64/stable/5f07056aad3ca18f717f05358cbf91cc4eaeb376a156a730fc83089fe4f9d6cf
Installed size: 145.8 MB
Runtime: org.gnome.Platform/x86_64/3.28
Sdk: org.gnome.Sdk/x86_64/3.28
```

### BUG
With only GNOME Terminal running (with some tabs running mosh and Eternal Terminal sessions) my Thinkpad's power drain is around 6W:
screenshot from 2018-08-20 17-20-28

Firing up UberWriter, even idling (no file open) and with the window not overlapping the terminal window, the power drain jumps to at least 15W:
screenshot from 2018-08-20 17-25-18

Is UberWriter doing excessive polling?

### LINKED ISSUE #90: [Feature Request] More format highlighting
Currently neither links or code blocks are highlighted in the editor. Block quotations would also be nice to have some different styling to, as well as footnotes and title blocks.

### LINKED ISSUE #120: Subsequent elements in a list are not properly indented to the left
Especially as a user of a unicode using keayboard (German Neo 2), I often itemize by the usage of more suiting characters like `•` (bullet), `–` (proper itemization dash) and `·` (centered dot), so my text also looks halfway marked up on non-Markdown text viewers.

Do you maybe like to handle these characters like `*` and `-` (hyphen!) are handled, and thus also use them for marking up itemizations?

### LINKED ISSUE #122: GitHub-flavored markdown?
### ENVIROMENT
- Linux distribution: Fedora 29
- Desktop Enviroment: Gnome
- DE version: 3.30
- GTK version: 3.24.1-2.fc29

### BUG

There are subtle differences in how markdown is handled in UberWriter, and most other places that use GitHub-flavored markdown (eg. GitHub itself, Twist, Typora, Slack, etc).

An example is how paragraphs are handled. Notice the difference:
Screenshot-20190320023204
Screenshot-20190320023214
Screenshot-20190320023118
Screenshot-20190320023125

I am not sure this is related with the (lack of?) support for GitHub-flavored markdown, or something else entirely. If it is the former, is there any chance we could add a toggle in the settings to have pandoc use the `gfm` input format?

### PR DESCRIPTION
**Pull request by goncalossilva**
This PR includes various fixes and improvements, most of which I discussed with @somas95 a couple of weeks ago. It also includes some refactoring, mainly to improve encapsulation.

Fixes #17  
Fixes #75 
Fixes #90 
Fixes #120
Fixes #122

Some considerations/questions follow.

**Commit messages**
I recommend reviewing each commit message carefully, as they explain the thinking behind each change. Not everything is small or linear, and hopefully the commit message explains the background and reasoning properly. If anything is missing, I'm happy to try to explain.

**Translations**
There are a few capitalization/copy fixes. I am unsure how this affects translations, or if there's any work I can to make the transition easier. For instance, how are the po files updated?

**Styling**
Styling is subjective, and although I claim to address #90, it's important to note that I'm a fan of UberWriter's simplistic style, reminiscent of iA Writer's approach. As such, I didn't introduce any sizing nor color changes, as I don't personally agree with this direction. Instead, the changes are subtle:
* For links, the link/syntax part is greyed out, without any further changes
* For code blocks, they are indented similarly to quotations, without any further changes

**UI changes**
There are (very minor) UI changes within the places that were touched, mainly preferences and the export dialog. Most of these are around improving small things, such as spacing (eg. multiples of 8), slightly broken alignments, etc.

The only exception would be the removal of ODT as one of the export options in the top bar. As before, subjective, but I find that a sub-window's top bar with 6 horizontal buttons is a little overwhelming, and considering that ODT is still available within the advanced tab, I propose that we remove it as a default option and have a more balanced top bar. I am assuming that PDF/HTML are the most used, but please let me know if that's not the case.

**Further work**
I have a few more tasks planned for the upcoming weeks, hopefully built on top of this codebase as it makes some of them much easier. [Here's a screenshot of my Todoist.](https://cl.ly/4160755d210d/gnome-shell-screenshot-3MMO0Z.png) Hopefully this helps knowing what to expect. :blush:

### CODE REVIEW

**Comment by goncalossilva** [comment]
I noticed it and it makes perfect sense. :+1: Did I miss it somewhere?

**Comment by somas95** [comment]
I've been testing this and I have a couple of comments, but first of all, thanks again for all of this.

> Did I miss it somewhere?

My fault, I didn't see https://github.com/UberWriter/uberwriter/pull/143/commits/41377c24bb60ac06365cb719a3f2c1947bd9aafc

Also, a lot of the following notes are for myself, I'll write some today and a lot more tomorrow. (I have little time from monday to thursday)

- The font sizes are broken. See https://github.com/UberWriter/uberwriter/issues/141#issuecomment-482955105 for how they should behave
- We'll need to package pypandoc and add it to the flatpak package. I can take care of that
- The export dialog throes this error: `filechooser.set_do_overwrite_confirmation(True)
AttributeError: 'NoneType' object has no attribute 'set_do_overwrite_confirmation'`
- The search function can go outside range. This happened before, and has no consequences, but this would be a good moment to fix it
-  Moving the pandoc documentation to the preferences dialog is a good idea, but the icon should be symbolic (I think)

I'll merge this in a working branch and push some changes there as soon as I can

**Comment by goncalossilva** [comment]
Thanks for reviewing @somas95! Looking forward for more feedback as well. :smile: 

> The font sizes are broken. See #141 (comment) for how they should behave

Hum, are they? There should be 66 characters per line on all 3 breakpoints. This was meant as an improvement, as it was a little variable before. Also, most research I can find does indeed point to the range in the other thread, but for screens 66 seems to be referenced very frequently, eg. ["The 66-character line(counting both letters and spaces) is widely regarded as ideal."](http://webtypography.net/2.1.2)

> We'll need to package pypandoc and add it to the flatpak package. I can take care of that

I don't know how this is done, but I'd love to learn. :smile: Could you make a commit and point me it?

> The export dialog throes this error

I will investigate this. I don't recall changing this function, but it might be a side-effect of another change.

> The search function can go outside range. This happened before, and has no consequences, but this would be a good moment to fix it

Agree, will investigate as well.

> Moving the pandoc documentation to the preferences dialog is a good idea, but the icon should be symbolic (I think)

Agree! This was the first time I was using Glade, and I couldn't find a nice way to use the symbolic version, but will investigate it more.

**Comment by goncalossilva** [comment]
Everything (except flatkpak which I honestly have no clue :sweat_smile:) should be addressed.

Font sizes: 8159ad9. I've also tweaked the workflow to instead of hard-coding widths, hard-coding font sizes. I would love to not hard-code any of them, but can't think of a good approach at the moment, and this seems like the best of two evils as it makes things easier to understand and change.

(One unrelated problem I noticed is that when viewing a large document and resizing the window, there will be some unwanted scroll upwards. This is also present in the production version. It will be a lot easier to fix this once I work on the scrolling sync, so I have added a task to address it then.)

Export dialog error: d98208e.

Search outside of bounds: 567e74c.

Symbolic info icon: 53d3fc6.

And a couple of tiny improvements along the way. Thanks again for trying it out and providing feedback!

**Comment by somas95** [comment]
Hooks for a proper localization workflow will come with meson...
Right now I commit everything back and forth between poeditor and github, with some tweaks along the way. It's more complicated than that, and it definitively could be improved. Right now the only drawback is that I have to do more work, but it's ok for the moment.

I'm going to merge into a working branch, and do some things with the font sizes thing. I think I have an idea

And I'll try to update the flatpak scripts

**Comment by somas95** [comment]
Well, I've been testing it a little more, and we still have issues with the scrolling/resizing behavior

##Issue 1
- Steps to reproduce:
--  Open any large file
--  Resize horizontally the window back and forth
- What happens:
- - The content starts to scroll up

ezgif-2-b4e14a0dd66a

##Issue 2
 - Steps to reproduce:
--  Open UberWriter on wayland
--  Resize horizontally the window back and forth / Open the recents menu
- What happens:
- - The size of the textview changes without reason

ezgif-2-78bb96332849

(I couldn't do a proper recording on this one because peek and wayland don't work well along)

Finally, I pushed some things to the flathub beta channel. See https://github.com/UberWriter/uberwriter/issues/111#issuecomment-484270019 for more info

**Comment by goncalossilva** [comment]
> Right now I commit everything back and forth between poeditor and github, with some tweaks along the way.

Huh, that sounds painful. :confused: Looking forward to the transition to Meson!

> I'm going to merge into a working branch, and do some things with the font sizes thing. I think I have an idea

Sounds good! Could you elaborate? I'm curious. :smile: 

> And I'll try to update the flatpak scripts

Thanks!

> The content starts to scroll up

Yes, this is the issue I documented before. I can reproduce it in the production version as well, so it is not new. I know how to fix this, but it's non-trivial and would be much easier after the scrolling workflow is improved (for scroll sync). I plan to address it then.

> The size of the textview changes without reason

This is a new issue, correct? Can you reproduce on X? I don't have access to a Wayland box, will try to set it up in a VM, but I think I know why this is happening.

**Comment by somas95** [comment]
>Sounds good! Could you elaborate? I'm curious. 😄
I want to try to invert the workflow: set the font size depending on the window width *and* the desired line length, which would be tweakable from dconf 
>This is a new issue, correct? Can you reproduce on X? I don't have access to a Wayland box, will try to set it up in a VM, but I think I know why this is happening.
No, it only happens on wayland. I noticed it testing some things in a silverblue VM (ostree systems cause a different set of bugs, but I want to support them too 🙄). Changed to a wayland gnome session on the host system and saw it there as well. It's not the first issue we have with wayland, but is the default desktop on fedora and silverblue, so a lot of people use it :/

**Comment by goncalossilva** [comment]
> set the font size depending on the window width and the desired line length

Ah, sounds like a great idea! Off the top of my head it can be troublesome to make the CSS work (most padding/margin/dimensions are font-size dependent), but if that is not problematic, it could be a really elegant approach.

> It's not the first issue we have with wayland, but is the default desktop on fedora and silverblue, so a lot of people use it 

Definitely, I will look into it. :+1:

**Pull request merged**
