### PR TITLE
Fix preview flash on toggle

### LINKED ISSUE #112: [Question] Preview flashes momentarily and goes blank - config issue? Workaround?
### ENVIRONMENT
- Linux distribution: Kubuntu 18.04.02
- Desktop Enviroment: KDE Plasma 
- DE version: 5.12.7
- GTK version: 3.22.30-1ubuntu2

### QUESTION
When I attempt to preview my Markdown (e.g. the included `uberwriter_markdown.md` tutorial), the preview appears momentarily, but vanishes after an instant, leaving me with a blank screen until I revert to the raw view. I assume that this is a local configuration issue (I've had problems with GTK Flatpaks before, for reasons unknown, and simply switched to `apt` repo versions instead). Would anyone know of possible workarounds that might solve this issue?

### WHAT I DID
I installed all of the packages mentioned as prerequisites in README.md (installing `webkit2gtk-driver` at version `2.22.6-0ubuntu0.18.04.01` via `apt`) and then installed the Flatpak like so:

```
$ flatpak install flathub de.wolfvollprecht.UberWriter
Looking for matches…
Required runtime for de.wolfvollprecht.UberWriter/x86_64/stable (runtime/org.gnome.Platform/x86_64/3.30) found in remote flathub
Do you want to install it? [Y/n]: y

de.wolfvollprecht.UberWriter permissions:
    ipc                   network       wayland      x11      file access [1]
    dbus access [2]

    [1] host, xdg-run/dconf, ~/.config/dconf:ro
    [2] ca.desrt.dconf


        ID                                          Arch     Branch  Op  Remote   Download
 1. [✓] org.gnome.Platform                          x86_64   3.30    i   flathub  301.7 MB / 419.3 MB
 2. [✓] org.gnome.Platform.Locale                   x86_64   3.30    i   flathub   17.0 kB / 223.0 MB
 3. [✓] org.freedesktop.Platform.GL.nvidia-390-48   x86_64   1.4     u   flathub   46.3 MB / 46.7 MB
 4. [✓] org.freedesktop.Platform.VAAPI.Intel        x86_64   18.08   i   flathub    1.8 MB / 1.8 MB
 5. [✓] org.freedesktop.Platform.html5-codecs       x86_64   18.08   i   flathub    2.7 MB / 2.9 MB
 6. [✓] de.wolfvollprecht.UberWriter                x86_64   stable  i   flathub   34.1 MB / 34.1 MB

Changes complete.
```

### PR DESCRIPTION
**Pull request by goncalossilva**
Fixes #112

### CODE REVIEW

**Comment by somas95** [comment]
What happened to this PR? It seemed promising

**Comment by goncalossilva** [comment]
I planned to make a few PRs with small isolated improvements, but in a couple of cases that would turn out to be unnecessarily complex (ie. merge struggles). I'll submit this again soon. :smile:

**Comment by somas95** [comment]
Cool! Did it solve the issue with the crash of the webview?
Btw, I'm sloowly refactoring the application, to break it into smaller modules. UberwriterWindow.py does too many things. We'll get there eventually 😅, in the meantime I'm sorry if it's difficult to do PR's and contributing in general

**Comment by goncalossilva** [comment]
Great to hear! I did struggle a little bit, but nothing much. Better modularity would of course make it easier, but it's not that bad. Personally, I find it much more important to be able to work with responsive maintainers... Kudos for that! :smile:

**Pull request closed without merging**
