### PR TITLE
Adding GPL-3 License file.

### PR DESCRIPTION
**Pull request by kshithijiyer**

### CODE REVIEW

**Comment by rusty-snake** [comment]
@kshithijiyer there is one. See [COPYING](https://github.com/UberWriter/uberwriter/blob/master/COPYING)

**Comment by kshithijiyer** [comment]
I feel it should be license and not copy.

**Comment by rusty-snake** [comment]
Why? Every GNU Software (including all GNOME Apps, GIMP, ...) has this. There is no problem.

**Comment by somas95** [comment]
https://www.gnu.org/licenses/gpl-howto.en.html
The COPYING file should suffice

**Pull request closed without merging**
